FROM node:22.9.0

WORKDIR /app

# Install required libraries for canvas and Playwright
RUN apt-get update && apt-get install -y \
  libcairo2-dev \
  libpango1.0-dev \
  libjpeg-dev \
  libgif-dev \
  librsvg2-dev \
  wget \
  unzip \
  fonts-liberation \
  libappindicator3-1 \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libcups2 \
  libdbus-1-3 \
  libgdk-pixbuf2.0-0 \
  libnspr4 \
  libnss3 \
  libx11-xcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  xdg-utils \
  && rm -rf /var/lib/apt/lists/*

# Install the necessary npm packages (including Playwright)
COPY package*.json ./
RUN npm install

# Install Playwright browsers
RUN npx playwright install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]